export const CONFIG_STATUS = {
  UPDATE_LANGUAGE: 'UPDATE_LANGUAGE',
  UPDATE_FONT_SIZE: 'UPDATE_FONT_SIZE',
  UPDATE_FONT_STYLE: 'UPDATE_FONT_STYLE',
  UPDATE_COLOR_MODE: 'UPDATE_COLOR_MODE',
  UPDATE_SHOW_BILINGUAL: 'UPDATE_SHOW_BILINGUAL',
  OVERRIDE_BY_SERVER: 'OVERRIDE_BY_SERVER',
  OVERRIDE_ALL: 'OVERRIDE_ALL',
};
