export const CONFIG_STATUS = {
  UPDATE_LANGUAGE: 'UPDATE_LANGUAGE',
  UPDATE_FONT_SIZE: 'UPDATE_FONT_SIZE',
  UPDATE_FONT_STYLE: 'UPDATE_FONT_STYLE',
  UPDATE_COLOR_MODE: 'UPDATE_COLOR_MODE',
  OVERRIDE_ALL: 'OVERRIDE_ALL',
};
