const EVENT_TYPE = {
  ENTER_APP: 'ENTER_APP',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  ENTER_STUDY_SCREEN: 'ENTER_STUDY_SCREEN',
  LEAVE_STUDY_SCREEN: 'LEAVE_STUDY_SCREEN',
};

export default EVENT_TYPE;
