export const EXT_STORAGE_CONFIG = 'EXT_STORAGE_CONFIG';

export const EXT_STORAGE_WORD_LIST = 'EXT_STORAGE_WORD_LIST';

export const STORAGE_USER = 'STORAGE_USER';

export const STORAGE_AUTH_TOKEN = 'STORAGE_AUTH_TOKEN';

export const STORAGE_CONFIG = 'STORAGE_CONFIG';
